training:
  model_dir: ./models
  batch_size: 128 
  num_exits: 16384 
  learning_rate: 0.005
  optimizer: adam
  weight_decay: 0.0001

walkers:
  time_step: 0.01

hardware:
  cuda: true 

model:
  name: "feed-forward"
  input_size: 2
  hidden_size: [256, 256, 256] 
  output_size: 1
