training:
  model_dir: ./models
  batch_size: 64
  num_exits: 32768
  learning_rate: 0.01
  optimizer: adam
  weight_decay: 0.0001

walkers:
  time_step: 0.01

hardware:
  cuda: true

model:
  name: "feed-forward"
  input_size: 2
  hidden_size: [128, 128, 128, 128] 
  output_size: 1
